=== ivc-inform/simplesys/xml-extender/src/test/resources/defs/bo/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0.0" targetNamespace="http://simpleSys.ru/xml/library/bo" xmlns="http://simpleSys.ru/xml/library/bo" attributeFormDefault="unqualified" elementFormDefault="qualified">

  <xs:simpleType name="domain">
    <xs:restriction base="xs:string">
      <xs:enumeration value="di"/>
      <xs:enumeration value="id"/>
      <xs:enumeration value="ss"/>
      <xs:enumeration value="bBoolean"/>
      <xs:enumeration value="dDate"/>
      <xs:enumeration value="dDateOptTime"/>
      <xs:enumeration value="dDateTime"/>
      <xs:enumeration value="dTimestamp"/>
      <xs:enumeration value="dTimestampWithTZ"/>
      <xs:enumeration value="sCode"/>
      <xs:enumeration value="sCaption"/>
      <xs:enumeration value="sDescription"/>
      <xs:enumeration value="sBarCode"/>
      <xs:enumeration value="sPostalIndex"/>
      <xs:enumeration value="sAddress"/>
      <xs:enumeration value="sPhone"/>
      <xs:enumeration value="sEMail"/>
      <xs:enumeration value="sURL"/>
      <xs:enumeration value="sURLDomain"/>
      <xs:enumeration value="nInt"/>
      <xs:enumeration value="fDouble"/>
      <xs:enumeration value="fSum"/>
      <xs:enumeration value="fPrice"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="hierarchyMapping">
    <xs:restriction base="xs:string">
      <xs:enumeration value="oneTablePerHierarchy"/>
      <xs:enumeration value="tablePerClass"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="uniqueList">
    <xs:restriction base="xs:string">
      <xs:enumeration value="pk"/>
      <xs:enumeration value="uq"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="linkList">
    <xs:restriction base="xs:string">
      <xs:enumeration value="assoc"/>
      <xs:enumeration value="refIsOwned"/>
      <xs:enumeration value="refIsOwner"/>
      <xs:enumeration value="refIsParent"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="objectSchema">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="groupType" name="group" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:complexType name="groupType">
    <xs:sequence>
      <xs:element type="classesType" name="classes" minOccurs="0" maxOccurs="1"/>
      <xs:element type="tablesType" name="tables" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="prefix" use="required"/>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="caption" use="required"/>
  </xs:complexType>

  <xs:complexType name="classesType">
    <xs:sequence>
      <xs:element type="classSimpleType" name="classSimple" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="systemEnumClassType" name="classEnum" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="classInHierarchyType" name="classInHierarchy" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tablesType">
    <xs:sequence>
      <xs:element type="tableType" name="table" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tableType">
    <xs:sequence>
      <xs:element type="columnsType" name="columns" maxOccurs="1" minOccurs="1"/>
      <xs:element type="constraintsType" name="constraints" maxOccurs="1" minOccurs="1"/>
    </xs:sequence>
    <xs:attributeGroup ref="basicTableGroup"/>
  </xs:complexType>


  <xs:attributeGroup name="basicTableGroup">
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:boolean" name="useNameAsIs" use="optional"/>
  </xs:attributeGroup>

  <xs:complexType name="columnsType">
    <xs:sequence>
      <xs:element type="columnType" name="column" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="columnType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="caption" use="optional"/>
        <xs:attribute type="domain" name="type" use="required"/>
        <xs:attribute type="xs:boolean" name="mandatory" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>


  <xs:attributeGroup name="basicClassGroup">
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="caption" use="optional"/>
    <xs:attribute type="xs:boolean" name="autoTableMapping" use="required"/>
  </xs:attributeGroup>


  <xs:attributeGroup name="hierarchyGroup">
    <xs:attribute type="hierarchyMapping" name="hierarchyMapping" use="optional"/>
    <xs:attribute type="xs:string" name="discriminatorField" use="optional"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="refToParentGroup">
    <xs:attribute type="xs:string" name="parent" use="optional"/>
    <xs:attribute type="xs:string" name="parentGroup" use="optional"/>
    <xs:attribute type="xs:string" name="discriminatorValue" use="optional"/>
  </xs:attributeGroup>


  <xs:complexType name="classSimpleType">
    <xs:sequence>
      <xs:element type="attrsType" name="attrs" maxOccurs="1" minOccurs="0"/>
      <xs:element type="constraintsType" name="constraints" maxOccurs="1" minOccurs="1"/>
    </xs:sequence>
    <xs:attributeGroup ref="basicClassGroup"/>
  </xs:complexType>

  <xs:complexType name="classInHierarchyType">
    <xs:sequence>
      <xs:element type="childClassType" name="referenceToParent" maxOccurs="1" minOccurs="0"/>
      <xs:element type="parentClassType" name="hierarchySettings" maxOccurs="1" minOccurs="0"/>
      <xs:element type="attrsType" name="attrs" maxOccurs="1" minOccurs="0"/>
      <xs:element type="constraintsForHierarchiesType" name="constraints" maxOccurs="1" minOccurs="0"/>
    </xs:sequence>
    <xs:attributeGroup ref="basicClassGroup"/>
    <xs:attribute type="xs:boolean" name="abstract" use="optional"/>
  </xs:complexType>


  <xs:complexType name="childClassType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attributeGroup ref="refToParentGroup"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="parentClassType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attributeGroup ref="hierarchyGroup"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="attrType">
    <xs:sequence>
      <xs:element type="valueType" name="value" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="domain" name="type" use="required"/>
    <xs:attribute type="xs:boolean" name="mandatory" use="required"/>
    <xs:attribute type="xs:boolean" name="calculated" use="optional"/>
    <xs:attribute type="xs:string" name="formula" use="optional"/>
    <xs:attribute type="xs:boolean" name="isSimpleEnum" use="optional"/>
    <xs:attribute name="useInDataSorces" type="xs:boolean" use="optional"/>
    <xs:attributeGroup ref="attrTypeAttributeGroup"/>
  </xs:complexType>


  <xs:complexType name="attrsType">
    <xs:sequence>
      <xs:element type="attrType" name="attr" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="valueType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="key" use="required"/>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="caption" use="required"/>
        <xs:attribute type="xs:string" name="description" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="systemEnumClassType">
    <xs:sequence>
      <xs:element type="valueType" name="value" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
    <xs:attributeGroup ref="basicClassGroup"/>
    <xs:attribute type="xs:string" name="keyAttr" use="required"/>
    <xs:attribute type="xs:string" name="nameAttr" use="required"/>
    <xs:attribute type="xs:string" name="captionAttr" use="required"/>
    <xs:attribute type="xs:string" name="descriptionAttr" use="required"/>
  </xs:complexType>

  <xs:complexType name="constraintsType">
    <xs:sequence>
      <xs:element type="uniqueType" name="uc" maxOccurs="unbounded" minOccurs="1"/>
      <xs:element type="foreignType" name="fk" maxOccurs="unbounded" minOccurs="0"/>
      <!--            <xs:element type="foreignTypeWeak" name="fkWeak" maxOccurs="unbounded" minOccurs="0"/>-->
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="constraintsForHierarchiesType">
    <xs:sequence>
      <xs:element type="uniqueType" name="uc" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="foreignType" name="fk" maxOccurs="unbounded" minOccurs="0"/>
      <!--            <xs:element type="foreignTypeWeak" name="fkWeak" maxOccurs="unbounded" minOccurs="0"/>-->
    </xs:sequence>
  </xs:complexType>


  <xs:attributeGroup name="constraintGroup">
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <!--
        <xs:attribute type="xs:string" name="suffix" use="optional"/>
-->
  </xs:attributeGroup>

  <xs:complexType name="uniqueType">
    <xs:sequence>
      <xs:element type="xs:string" name="attrName" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
    <xs:attributeGroup ref="constraintGroup"/>
    <xs:attribute type="uniqueList" name="uniqueType" use="required"/>
  </xs:complexType>

  <xs:complexType name="foreignType">
    <xs:sequence>
      <xs:element type="foreignFieldType" name="mapping" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
    <xs:attributeGroup ref="constraintGroup"/>
    <xs:attribute type="xs:string" name="parent" use="required"/>
    <xs:attribute type="xs:string" name="parentGroup" use="optional"/>
    <xs:attribute type="linkList" name="linkType" use="required"/>
  </xs:complexType>

  <!--    <xs:complexType name="foreignTypeWeak">
        <xs:attributeGroup ref="constraintGroup"/>
        <xs:attribute type="xs:string" name="parent" use="required"/>
        <xs:attribute type="xs:string" name="parentGroup" use="optional"/>
        <xs:attribute type="linkList" name="linkType" use="required"/>
        <xs:attribute type="xs:string" name="columnPrefix" use="optional"/>
        <xs:attribute type="xs:boolean" name="mandatory" use="required"/>
    </xs:complexType>-->


  <xs:complexType name="foreignFieldType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="attrNameLocal" use="required"/>
        <xs:attribute type="xs:string" name="attrNameRemote" use="required"/>
        <xs:attribute type="xs:string" name="caption" use="optional"/>
        <xs:attribute type="xs:boolean" name="mandatory" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>


  <xs:attributeGroup name="attrTypeAttributeGroup">
    <xs:attribute type="xs:string" name="caption" use="optional"/>
    <xs:attribute name="hidden" type="xs:boolean" use="optional"/>
  </xs:attributeGroup>
</xs:schema>

=== ivc-inform/simplesys/xml-extender/src/test/resources/defs/bo/test.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE objectSchema []>
<objectSchema xmlns="http://simpleSys.ru/xml/library/bo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://simpleSys.ru/xml/library/bo schema.xsd">
  <group prefix="TST" name="test" caption="Тесты">
    <classes>
      <classSimple name="TestDataTypes" autoTableMapping="true" caption="Тесты типов данных">
        <attrs>
          <attr name="di" type="di" mandatory="true"/>
          <attr name="nInt" type="nInt" mandatory="true"/>

          <attr name="testRef" type="ss" mandatory="true"/>
          <attr name="testRefOpt" type="ss" mandatory="false"/>

        </attrs>
        <constraints>
          <uc uniqueType="pk">
            <attrName>di</attrName>
          </uc>

          <!--                    <fk parentGroup="refs" parent="DocState" linkType="assoc">
                                  <mapping attrName="testRef" attrNameFK="ss"/>
                              </fk>
                              <fk parentGroup="refs" parent="DocState"  linkType="assoc">
                                  <mapping attrName="testRefOpt" attrNameFK="ss"/>
                              </fk>-->


        </constraints>
      </classSimple>
      <classSimple name="TestDoc" autoTableMapping="true" caption="Тестовый документ">
        <attrs>
          <attr name="di" type="di" mandatory="true"/>
          <attr name="numDoc" type="sCode" mandatory="true" caption="Номер документа"/>
          <attr name="dateExec" type="dDateTime" mandatory="false" caption="Дата исполнения"/>
          <!--attr name="state" type="ss" mandatory="true" caption="Состояние документа"/-->
          <attr name="fsmState" type="ss" mandatory="false" isSimpleEnum="true">
            <value key="D" name="draft" caption="Черновик"/>
            <value key="E" name="executing" caption="Исполняется"/>
            <value key="EW" name="executingWWrnt" caption="Исполняется, есть СО"/>
            <value key="C" name="closed" caption="Закрыт"/>
            <value key="CC" name="closedAndCostCalc" caption="Закрыт, участвует в распр.себестоимости"/>
            <value key="A" name="archived" caption="В архиве"/>
            <value key="AN" name="annulled" caption="Аннулирован"/>
            <value key="DR" name="dropped" caption="Удален"/>
          </attr>
        </attrs>
        <constraints>
          <uc uniqueType="pk">
            <attrName>di</attrName>
          </uc>
          <!--fk parent="DocState" parentGroup="refs" linkType="assoc">
              <mapping attrName="state" attrNameFK="ss"/>
          </fk-->
          <fk parent="DocState" parentGroup="refs" linkType="assoc">
            <mapping attrNameLocal="docState" attrNameRemote="ss" mandatory="true" caption="Состояние теста"/>
          </fk>

        </constraints>
      </classSimple>
    </classes>
  </group>
</objectSchema>

=== ivc-inform/simplesys/xml-extender/src/test/resources/defs/bo/organizational.xml
<?xml version="1.0" encoding="UTF-8"?>

<objectSchema xmlns="http://simpleSys.ru/xml/library/bo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://simpleSys.ru/xml/library/bo schema.xsd">
  <group prefix="ORG" name="organizational" caption="Орг.структура">
    <classes>
      <classSimple name="Division" caption="Подразделение" autoTableMapping="true">
        <attrs>
          <attr name="di" type="di" mandatory="true"/>
          <attr name="code" type="sCode" caption="Мнемокод" mandatory="false"/>
          <attr name="caption" type="sCaption" caption="Наименование" mandatory="true"/>
          <attr name="description" type="sDescription" caption="Описание" mandatory="false"/>
        </attrs>
        <constraints>
          <uc uniqueType="pk">
            <attrName>di</attrName>
          </uc>
          <fk parent="Division" linkType="refIsOwner">
            <mapping attrNameLocal="parent" attrNameRemote="di" caption="Родительское подразделение" mandatory="false"/>
          </fk>
        </constraints>
      </classSimple>

      <classSimple name="Jur" caption="Юр.лицо" autoTableMapping="true">
        <attrs>
          <attr name="di" type="di" mandatory="true"/>
          <attr name="code" type="sCode" caption="Мнемокод" mandatory="false"/>
          <attr name="caption" type="sCaption" caption="Наименование" mandatory="true"/>
          <!--attr name="jurContractor" type="di" caption="Контрагент юр.лица" mandatory="true"/-->
          <attr name="description" type="sDescription" caption="Описание" mandatory="false"/>
        </attrs>
        <constraints>
          <uc uniqueType="pk">
            <attrName>di</attrName>
          </uc>
          <fk linkType="assoc" parent="JurContractor" parentGroup="common">
            <mapping attrNameLocal="jurContractor" attrNameRemote="di" mandatory="true"/>
          </fk>
        </constraints>
      </classSimple>

      <classInHierarchy name="Branch" abstract="true" autoTableMapping="true">
        <hierarchySettings discriminatorField="isExternal" hierarchyMapping="oneTablePerHierarchy"/>
        <attrs>
          <attr name="di" type="di" mandatory="true"/>
          <attr name="code" type="sCode" caption="Код" mandatory="false"/>
          <attr name="caption" type="sCaption" caption="Наименование" mandatory="true"/>
          <attr name="isExternal" type="bBoolean" caption="Внешняя БЕ" mandatory="true"/>
          <attr name="description" type="sDescription" caption="Описание" mandatory="false"/>
        </attrs>
        <constraints>
          <uc uniqueType="pk">
            <attrName>di</attrName>
          </uc>
        </constraints>
      </classInHierarchy>
      <classInHierarchy name="BranchInt" autoTableMapping="true">
        <referenceToParent parent="Branch" discriminatorValue="false"/>
        <attrs>
          <attr name="hzz" type="sCaption" mandatory="true"/>
        </attrs>
      </classInHierarchy>
      <classInHierarchy name="BranchExt" autoTableMapping="true">
        <referenceToParent parent="Branch" discriminatorValue="true"/>
        <attrs>
          <attr name="hzzzzz2" type="sCaption" mandatory="true"/>
        </attrs>
      </classInHierarchy>

    </classes>
  </group>
</objectSchema>

=== ivc-inform/simplesys/xml-extender/src/test/resources/defs/bo/sequences.xml
<?xml version="1.0" encoding="UTF-8"?>
<objectSchema xmlns="http://simpleSys.ru/xml/library/bo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://simpleSys.ru/xml/library/bo schema.xsd">
  <group prefix="SVC" name="systemservice" caption="Сиквенсы и прочее">
    <classes>
      <classSimple name="SeqGenerator" autoTableMapping="true" caption="Учет последовательных идентификаторов (ID)">
        <attrs>
          <attr name="nameSeq" type="sCode" mandatory="true"/>
          <attr name="maxValue" type="nInt" mandatory="true"/>
        </attrs>
        <constraints>
          <uc uniqueType="pk">
            <attrName>nameSeq</attrName>
          </uc>
        </constraints>
      </classSimple>
    </classes>
  </group>
</objectSchema>

=== ivc-inform/simplesys/xml-extender/src/test/resources/defs/bo/currency.xml
<?xml version="1.0" encoding="UTF-8"?>

<objectSchema xmlns="http://simpleSys.ru/xml/library/bo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://simpleSys.ru/xml/library/bo schema.xsd">
  <group prefix="CUR" name="currency" caption="Валюта и связанные объекты">
    <classes>
      <classSimple name="Currency" caption="Валюта" autoTableMapping="true">
        <attrs>
          <attr name="di" type="di" mandatory="true"/>
          <attr name="caption" type="sCaption" mandatory="true"/>
          <attr name="description" type="sDescription" mandatory="false"/>
        </attrs>
        <constraints>
          <uc uniqueType="pk">
            <attrName>di</attrName>
          </uc>
        </constraints>
      </classSimple>
    </classes>
  </group>
</objectSchema>

=== ivc-inform/simplesys/xml-extender/src/test/resources/defs/bo/ui.xml
<?xml version="1.0" encoding="UTF-8"?>

<objectSchema xmlns="http://simpleSys.ru/xml/library/bo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://simpleSys.ru/xml/library/bo schema.xsd">
  <group prefix="UI" name="ui" caption="Карта сайта">
    <classes>

      <classSimple name="SiteMap" autoTableMapping="true" caption="Карта сайта">
        <attrs>
          <attr name="di" type="di" mandatory="true"/>
          <attr name="code" type="sCode" mandatory="true"/>
          <attr name="caption" type="sCaption" mandatory="true"/>
          <attr name="icon" type="sURL" mandatory="false"/>
        </attrs>
        <constraints>
          <uc uniqueType="pk">
            <attrName>di</attrName>
          </uc>
          <uc uniqueType="uq">
            <attrName>code</attrName>
          </uc>
          <fk parent="SiteMap" linkType="refIsOwner">
            <mapping attrNameLocal="parent" attrNameRemote="di" mandatory="false"/>
          </fk>
        </constraints>
      </classSimple>
    </classes>

  </group>
</objectSchema>

=== ivc-inform/simplesys/xml-extender/src/test/resources/defs/bo/common.xml
<?xml version="1.0" encoding="UTF-8"?>
<objectSchema xmlns="http://simpleSys.ru/xml/library/bo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://simpleSys.ru/xml/library/bo schema.xsd">
  <group prefix="CMN" name="common" caption="Общие объекты">
    <classes>
      <classSimple name="ContractorGroup" autoTableMapping="true">
        <attrs>
          <attr name="di" type="di" mandatory="true"/>
          <attr name="caption" type="sCaption" mandatory="true"/>
          <attr name="description" type="sDescription" mandatory="false"/>
        </attrs>
        <constraints>
          <uc uniqueType="pk">
            <attrName>di</attrName>
          </uc>
          <fk parent="ContractorGroup" linkType="refIsOwner">
            <mapping attrNameLocal="parent" attrNameRemote="di" mandatory="false"/>
          </fk>
        </constraints>
      </classSimple>
      <classInHierarchy name="Contractor" abstract="true" autoTableMapping="true" caption="Контрагенты">
        <hierarchySettings discriminatorField="isJur" hierarchyMapping="tablePerClass"/>
        <attrs>
          <attr name="di" type="di" mandatory="true"/>
          <attr name="isJur" type="bBoolean" mandatory="true"/>
          <attr name="caption" type="sCaption" caption="Наименование" mandatory="true"/>
          <attr name="description" type="sDescription" caption="Описание" mandatory="false"/>
        </attrs>
        <constraints>
          <uc uniqueType="pk">
            <attrName>di</attrName>
          </uc>
          <fk parent="ContractorGroup" linkType="assoc">
            <mapping attrNameLocal="group" attrNameRemote="di" mandatory="true" caption="Группа"/>
          </fk>
        </constraints>
      </classInHierarchy>

      <classInHierarchy name="JurContractor" autoTableMapping="true" caption="Юридические лица">
        <referenceToParent parent="Contractor" discriminatorValue="true"/>
        <attrs>
          <attr name="jurName" caption="Юр.лицо" type="sCaption" mandatory="true"/>
          <attr name="caption" type="sCaption" caption="Наименование" mandatory="true" calculated="true" formula="jurName"/>
        </attrs>
      </classInHierarchy>

      <classInHierarchy name="PhysContractor" autoTableMapping="true" caption="Физические лица">
        <referenceToParent parent="Contractor" discriminatorValue="false"/>
        <attrs>
          <attr name="lastName" caption="Фамилия" type="sCaption" mandatory="true"/>
          <attr name="firstName" caption="Имя" type="sCaption" mandatory="true"/>
          <attr name="secondName" caption="Отчество" type="sCaption" mandatory="false"/>
          <attr name="caption" type="sCaption" caption="Наименование" mandatory="true" calculated="true"
                formula="lastName + &quot; &quot; + firstName + secondName.map(&quot; &quot; + _).getOrElse(&quot;&quot;)"/>
        </attrs>
      </classInHierarchy>
    </classes>
  </group>
</objectSchema>

=== ivc-inform/simplesys/xml-extender/src/test/resources/defs/bo/stock.xml
<?xml version="1.0" encoding="UTF-8"?>

<objectSchema xmlns="http://simpleSys.ru/xml/library/bo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://simpleSys.ru/xml/library/bo schema.xsd">
  <group prefix="STK" name="stock" caption="Склады и СО">
    <classes>
      <classSimple name="Stock" autoTableMapping="true" caption="Склад">
        <attrs>
          <attr name="di" type="di" mandatory="true"/>
          <attr name="code" type="sCode" mandatory="false" caption="Код"/>
          <attr name="caption" type="sCaption" mandatory="false" caption="Наименование"/>
        </attrs>
        <constraints>
          <uc uniqueType="pk">
            <attrName>di</attrName>
          </uc>
          <fk parent="Division" parentGroup="organizational" linkType="assoc">
            <mapping attrNameLocal="division" attrNameRemote="di" mandatory="true" caption="Подразделение"/>
          </fk>
        </constraints>
      </classSimple>

    </classes>
  </group>
</objectSchema>

=== ivc-inform/simplesys/xml-extender/src/test/resources/defs/bo/gdsandservice.xml
<?xml version="1.0" encoding="UTF-8"?>

<objectSchema xmlns="http://simpleSys.ru/xml/library/bo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://simpleSys.ru/xml/library/bo schema.xsd">
  <group prefix="GS" name="gdsandservice" caption="Справочники ТМЦ">
    <classes>

      <classInHierarchy name="GdsAndSrv" autoTableMapping="true" caption="Товар/Услуга" abstract="true">
        <hierarchySettings discriminatorField="isGds" hierarchyMapping="tablePerClass"/>
        <attrs>
          <attr name="di" type="di" mandatory="true"/>
          <attr name="code" type="sCode" mandatory="false" caption="Код"/>
          <attr name="caption" type="sCaption" mandatory="true" caption="Наименование"/>
          <attr name="isGds" type="bBoolean" mandatory="true"/>
        </attrs>
        <constraints>
          <uc uniqueType="pk">
            <attrName>di</attrName>
          </uc>
          <fk parent="Measure" parentGroup="measure" linkType="assoc">
            <mapping attrNameLocal="baseMsm" attrNameRemote="di" mandatory="true" caption="Базовая ЕИ"/>
          </fk>
        </constraints>
      </classInHierarchy>

      <classInHierarchy name="Gds" autoTableMapping="true" caption="Товар">
        <referenceToParent discriminatorValue="true" parent="GdsAndSrv"/>
        <attrs>
          <attr name="hzzz" type="sCaption" mandatory="true"/>
        </attrs>
      </classInHierarchy>

      <classInHierarchy name="Service" autoTableMapping="true" caption="Услуга">
        <referenceToParent discriminatorValue="true" parent="GdsAndSrv"/>
        <attrs>
          <attr name="hzzz2" type="sCaption" mandatory="true"/>
        </attrs>
      </classInHierarchy>

    </classes>
  </group>
</objectSchema>
